#!/bin/bash
sudo chown root:root file1.txt.gpg
sudo chmod 400 file1.txt.gpg
sudo chown root:root file2.txt.gpg
sudo chmod 400 file2.txt.gpg
sudo chown root:root file3.txt
sudo chmod 404 file3.txt
sudo chown root:root file4.txt
sudo chmod 644 file4.txt
sudo chown root:root file5
sudo chmod 000 file5
sudo chown root:root file6.txt
sudo chmod 400 file6.txt
sudo chown root:root file7.txt
sudo chmod 400 file7.txt
sudo chown root:root file8.txt
sudo chmod 777 file8.txt
sudo chown root:root file9.txt
sudo chmod 777 file9.txt
sudo chown root:root privkey
sudo chmod 400 privkey
