sudo chown decal:decal file1.txt.gpg
sudo chown decal:decal file2.txt.gpg
sudo chown decal:decal file3.txt
sudo chown decal:decal file4.txt
sudo chown decal:decal file5
sudo chown decal:decal file6.txt
sudo chown decal:decal file7.txt
sudo chown decal:decal file8.txt
sudo chown decal:decal file9.txt
sudo chown decal:decal privkey
